### ISSUE TITLE
FOSUSER Issue , Cannot login as ROLE_ADMIN

### ISSUE THREAD

**Issue by yudhir** [kevinpapst/AdminLTEBundle-Demo#6]
In the Demo app as well as my own implementation based on the FOSUSER + ADMIN LTE ,  I am unable to login as ROLE ADMIN  after promoting User from bin/console fos : promote commands. 

What could be the reason for this?

**Comment by kevinpapst** [comment]
Thanks for the info, it is fixed with the latest commit.

If you used this demo as base, then you can copy & paste this method to your entity:
https://github.com/kevinpapst/AdminLTEBundle-Demo/blob/master/src/Entity/User.php#L50
