### ISSUE TITLE
404 error - The requested URL /en/ was not found on this server.

### ISSUE THREAD

**Issue by MyLabBook** [kevinpapst/AdminLTEBundle-Demo#7]
Installed this demo on Ubuntu 18 using composer and am running it through apache2 instead of ./bin/console. If I have indexing turned on in apache and when I start from the root directory, I can see the app successfully at the public subdirectory. However, selecting any of the menu items, or setting the default directory in apache to use the public subdirectory, gives the following error. 

The requested URL /en/ was not found on this server.

The /en/ is being appended to the URL by the /config/services.yaml file apparently, but that is causing the 404 error. 

I have tried with and without running npm and yarn, with the same results.

**Comment by MyLabBook** [comment]
OK. I found the solution. I did not have the Rewrite enabled in my apache config file. So I added the following. 

                       RewriteEngine on
                        RewriteBase /
                        RewriteCond %{REQUEST_FILENAME} !-f
                        RewriteCond %{REQUEST_FILENAME} !-d
                        RewriteRule ^(.*)$ index.php?q=$1 [L,QSA]
 
Now it works.

**Comment by kevinpapst** [comment]
Thanks for your feedback. I never thought that someone would setup a VirtualHost for it. 
Symfony has godd docuemntation about it as well (just dropping it here, if someone else searches for it in the future):
https://symfony.com/doc/current/setup/web_server_configuration.html

**Comment by Vikashdhruv70** [comment]
whever i runnnig ip it is showing like this. 
![Screenshot (213)](https://user-images.githubusercontent.com/58592118/91474886-77d07c80-e8b8-11ea-8ea9-66383022ae59.png)
